######################################################################
# Automatically generated by qmake (3.0) qui mar 13 23:17:40 2014
######################################################################

TEMPLATE = app
TARGET = interface
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += MainWindow.h
SOURCES += main.cpp MainWindow.cpp
